### PR TITLE
Enhance torso path planner

### PR DESCRIPTION
**Pull request by LinYuChi**
Add the torso path planner, and the function to generate virtual torso path given the contact state in contact planner.

### CODE REVIEW

**Comment by LinYuChi** [comment]
@chenxgu  You can take a look at the changes, but I will guide you through it later when you are going to use it.

**Comment by LinYuChi** [comment]
I will not merge it yet because that would require me to set up some third party dependencies on your computer in order to build this version of the codes. I will do that in the weekend.

**Comment by chenxgu** [comment]
Thank you! I will work in lab this weekend.

**Comment by LinYuChi** [comment]
I set up the 3rd party libraries to build this version of the code on armoire, so I am going to merge it. I modify only the NeuralNetworkInterface.cpp in escher_openrave_cpp to match this version to reflect api changes in some third party libraries, but I did not change anything in other C++ and python codes. You can pull the merged code anytime you find appropriate.

**Pull request merged**
